import { Component } from '@angular/core';

@Component({
  selector: 'app-order-details',
  imports: [],
  templateUrl: './order-details.component.html',
  styleUrl: './order-details.component.scss'
})
export class OrderDetailsComponent {
Courses= [
    {
      "id": "123143",
      "hours": 22,
      "image": "https://i.postimg.cc/DfNJZ1JC/full-stack.png",
      "level": "Beginner",
      "price": 199.9,
      "title": "Full Stack Web Development",
      "author": "Jane Doe",
      "category": "Development",
      "discount": 20,
      "lectures": 155,
      "addToCart": true,
      "categoryID": 1,
      "description": "Learn to build dynamic web applications from the ground up. This course covers HTML, CSS, JavaScript, and backend technologies like Node.js and Express. You'll also explore databases with MongoDB and gain experience in deploying applications.",
      "ratingCount": 150,
      "showOnHomepage": true
    },
    {
      "id": "452223",
      "hours": 42,
      "image": "https://i.postimg.cc/0Ntm0Fjv/mobile-development.png",
      "level": "Beginner",
      "price": 249.9,
      "title": "Mobile App Development",
      "author": "John Smith",
      "category": "Development",
      "discount": 0,
      "lectures": 115,
      "addToCart": false,
      "categoryID": 1,
      "description": "Dive into mobile app development using React Native. This course teaches you how to create cross-platform applications for iOS and Android, leveraging JavaScript and React. You'll learn about UI components, state management, and integrating with APIs.",
      "ratingCount": 200,
      "showOnHomepage": true
    },
    {
      "id": "223345",
      "hours": 22,
      "image": "https://i.postimg.cc/DfNJZ1JC/full-stack.png",
      "level": "Intermediate",
      "price": 179.9,
      "title": "Python for Data Science",
      "author": "Alice Johnson",
      "category": "Data Science",
      "discount": 10,
      "lectures": 30,
      "addToCart": false,
      "categoryID": 2,
      "description": "Explore the fundamentals of Python programming with a focus on data analysis and visualization. This course covers libraries like Pandas, NumPy, and Matplotlib, and introduces you to machine learning concepts using Scikit-learn.",
      "ratingCount": 120,
      "showOnHomepage": false
    },
    {
      "id": "243252",
      "hours": 18,
      "image": "https://i.postimg.cc/xTrm5KfX/devops.png",
      "level": "Beginner",
      "price": 199.9,
      "title": "DevOps Essentials",
      "author": "Mike Brown",
      "category": "DevOps",
      "discount": 10,
      "lectures": 10,
      "addToCart": true,
      "categoryID": 3,
      "description": "Understand the principles of DevOps and how to implement a continuous integration and continuous deployment (CI/CD) pipeline. This course covers tools like Docker, Jenkins, and Kubernetes, emphasizing collaboration between development and operations teams.",
      "ratingCount": 75,
      "showOnHomepage": true
    },
    {
      "id": "655765",
      "hours": 10,
      "image": "https://i.postimg.cc/52bCdbF1/cloud-computing.png",
      "level": "Beginner",
      "price": 149.9,
      "title": "Cloud Computing",
      "author": "Sara Lee",
      "category": "Cloud Computing",
      "discount": 25,
      "lectures": 10,
      "addToCart": false,
      "categoryID": 4,
      "description": "Get started with cloud computing concepts and services. This course covers major cloud platforms like AWS, Azure, and Google Cloud. You'll learn about cloud architecture, deployment models, and how to manage cloud resources effectively.",
      "ratingCount": 90,
      "showOnHomepage": false
    },
    {
      "id": "356093",
      "hours": 58,
      "image": "https://i.postimg.cc/qRPNmTdP/javascript.png",
      "level": "Intermediate",
      "price": 259.9,
      "title": "JavaScript Algorithms",
      "author": "Tom Wilson",
      "category": "Development",
      "discount": 25,
      "lectures": 50,
      "addToCart": false,
      "categoryID": 1,
      "description": "Master JavaScript by diving into algorithms and data structures. This course focuses on problem-solving techniques, performance optimization, and algorithmic thinking, helping you prepare for technical interviews and improve your coding skills.",
      "ratingCount": 180,
      "showOnHomepage": true
    },
    {
      "id": "987654",
      "hours": 30,
      "image": "https://i.postimg.cc/qRPNmTdP/javascript.png",
      "level": "Advanced",
      "price": 299.9,
      "title": "Advanced React",
      "author": "Emily Davis",
      "category": "Development",
      "discount": 15,
      "lectures": 40,
      "addToCart": true,
      "categoryID": 1,
      "description": "Deepen your understanding of React and learn advanced concepts such as hooks, context, and performance optimization to build complex applications.",
      "ratingCount": 95,
      "showOnHomepage": false
    },
    {
      "id": "876543",
      "hours": 25,
      "image": "https://i.postimg.cc/52bCdbF1/cloud-computing.png",
      "level": "Intermediate",
      "price": 219.9,
      "title": "Machine Learning Fundamentals",
      "author": "David Lee",
      "category": "Data Science",
      "discount": 20,
      "lectures": 45,
      "addToCart": false,
      "categoryID": 2,
      "description": "Gain a solid foundation in machine learning concepts and techniques, including supervised and unsupervised learning, regression, and classification.",
      "ratingCount": 130,
      "showOnHomepage": true
    }
  ]
}
